### PR TITLE
Add OS .svg icons, lost with move from Google Drive hosting to GH

### PR DESCRIPTION
**Pull request by LarryLACa**
Restore the OS icon.svg files previously used in the Google Drive hosted version of current-versions:
  old public Chrome Channel Releases URL, now fails since Google Drive hosting discontinued: https://9e464270f9dc1851bd6dff234d7c7c26fea90b42.googledrive.com/host/0B8R1QvA3x5IbWll3M0hIYXVLZlk/
   underlying Google Drive URL: 
       https://drive.google.com/drive/folders/0B8R1QvA3x5IbWll3M0hIYXVLZlk
The .svg files were copied from here to my [this] branch.

If the file omission was intentional, OK to ignore this request.

### CODE REVIEW

**Comment by LarryLACa** [comment]
Signed the CLA 

```
On Tuesday, November 15, 2016 12:53 PM, googlebot <notifications@github.com> wrote:
```

 Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). 📝 Please visit https://cla.developers.google.com/ to sign.Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.   
- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
- If you signed the CLA as a corporation, please let us know the company's name.

**Review by Garbee — APPROVED** [review]
LGTM

**Comment by LarryLACa** [comment]
Will check back in a few days to see if the files were added to the gh-pages branch.

**Comment by Garbee** [comment]
Just manually tested and it works fine locally (just missing Windows.) But, that isn't a big deal, merging on through now.

Thanks for fixing this, the display looks nicer with the system icons.

**Pull request merged**
