### PR TITLE
Add win.svg only

### PR DESCRIPTION
**Pull request by LarryLACa**
Added win.svg.  Was in my local test dir, but forgot the upload.

### CODE REVIEW

**Comment by LarryLACa** [comment]
Did I miss something?  Waiting for the Windows.svg merge back to base.

**Comment by Garbee** [comment]
Didn't miss anything. I'm just busy and lose track of GH notifications too easily.

Why is this touching other SVG's? If the point is to fix the windows icon it should only be changing what is needed for that. From what I'm seeing you've PRed the same commits again from the previous PR.

**Comment by LarryLACa** [comment]
My bad.  Still working thru GH101.  I intended to add only win.svg.  I thought my commit 5f9c6d7 was only for the single file and the PR Patch1#4, would only sweep in win.svg.  Is there a better way to pull only win.svg?

**Comment by Garbee** [comment]
I just cherry picked it in. Should be live soonish. Just needed to verify that was the only commit that was needed.

Thank you!

https://github.com/GoogleChrome/current-versions/commit/805d43339611b5348e60c411ee9668181b7f63ec

**Comment by LarryLACa** [comment]
Thanks.  Happy Holidays 

    On Tuesday, December 27, 2016 11:25 AM, Jonathan Garbee <notifications@github.com> wrote:
 

 I just cherry picked it in. Should be live soonish. Just needed to verify that was the only commit that was needed.Thank you!805d433—

**Pull request closed without merging**
